name: ghaith_test
description: "Technical Test Flutter - Task Management App by Ghaith"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Responsive UI
  flutter_screenutil: ^5.9.3

  lottie: ^3.2.0
  animate_do: ^4.2.0

  # State Management
  provider: ^6.1.2

  # Dialogs
  panara_dialogs: ^0.1.5

  # API / HTTP simulation
  dio: ^5.7.0

  # GPS & Map
  geolocator: ^14.0.2
  geolocator_android: ^5.0.2
  google_maps_flutter: ^2.7.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tasks.json
    - assets/lottie/
