name: ghaith_test
description: "Technical Test Flutter by Ghaith"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Responsive UI
  flutter_screenutil: ^5.9.3

  # State Management
  provider: ^6.1.2

  # API / HTTP simulation
  dio: ^5.7.0

  # JSON local support
  flutter/services.dart: any 

  #  GPS & Map
  geolocator: ^11.1.0
  google_maps_flutter: ^2.7.0

 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tasks.json
     #- assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
